### ISSUE TITLE
fail to create a page from a template with formula

### ISSUE THREAD

**Issue by nakamasato** [nakamasato/autonote#70]
```
Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/autodoc/.venv/lib/python3.9/site-packages/notion_client/client.py", line 118, in _parse_response
    response.raise_for_status()
  File "/Users/m.naka/repos/nakamasato/autodoc/.venv/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages/cce21b86-cf2a-4dd0-a463-ed5b1d29745f'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/autodoc/examples/create_notion_page_from_template_with_value_content.py", line 19, in <module>
    client.create_page_from_template(
  File "/Users/m.naka/repos/nakamasato/autodoc/src/autonote/notion.py", line 246, in create_page_from_template
    res = self.client.pages.update(
  File "/Users/m.naka/repos/nakamasato/autodoc/.venv/lib/python3.9/site-packages/notion_client/api_endpoints.py", line 220, in update
    return self.parent.request(
  File "/Users/m.naka/repos/nakamasato/autodoc/.venv/lib/python3.9/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
  File "/Users/m.naka/repos/nakamasato/autodoc/.venv/lib/python3.9/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.properties.Link.id should be defined, instead was `undefined`.
body.properties.Link.name should be defined, instead was `undefined`.
body.properties.Link.start should be defined, instead was `undefined`.
```

**Comment by nakamasato** [comment]
if you set the formula field to None
```py
pages_kwargs['properties']['Link'] = None
```

get the following error:

```
notion_client.errors.APIResponseError: Couldn't find editable properties for these identifiers: Link
```
